name: Build and Test C Project

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build C project
      run: |
        cd proyecto1
        gcc -o ejecutableProyecto1 main.c contrasena.c

    - name: Create test user file
      run: |
        cd proyecto1
        echo "TestUser1" > test_user.txt
        echo "TestPassword1" >> test_user.txt

    - name: Run the program with test user data
      run: |
        cd proyecto1
        ./ejecutableProyecto1 < test_user.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ejecutableProyecto1
        path: proyecto1/ejecutableProyecto1
