name: Build C Project

on: [push]  # Ejecutar la acción en cada push al repositorio

jobs:
  build:
    runs-on: ubuntu-latest  # Selecciona el sistema operativo en el que deseas compilar (Ubuntu en este caso)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Acción para clonar el repositorio en el entorno de trabajo

    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Build C project
      run: |
        cd proyecto1  # Navegar a la carpeta del proyecto
        gcc -o ejecutableProyecto1.exe main.c -mwindows  # compila el proyecto y genera el ejecutable para Windows

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ejecutableProyecto1
        path: proyecto1/ejecutableProyecto1.exe  # Ruta al archivo ejecutable compilado para Windows
